[neuron]

# number of neurons
neuron_count = 12

# number of input type neurons
input_neuron_count = 6

# number of groups
group_count = 3

# number of connections
edge_count = 10

# in milliseconds
wait_time = 200

# integer
wait_loops = 3

# value each neuron is initialized with
initial_membrane_potential = -55.0

# minimum potential at which a neuron will fire
activation_threshold = -55.0

# value that each neuron is set to after firing
refractory_membrane_potential = -70.0

# duration in milliseconds
refractory_duration = 2.0

# tau for the linearlization of the decay function
tau = 10.0

[debug]
# Options are
# INFO
# DEBUG
# DEBUG2
# DEBUG3
# DEBUG4
level = "DEBUG"

[decay]
# Value that each neuron decays every wait_time * wait_loops
value = 0.5


[random]
# options are 'time' for using the current time, or an integer (as a string e.g. "1")
seed = "1"

[runtime_vars]
# in seconds
runtime = 10

# file to read input from
input_file = "./input_files/test"
