[neuron]

# number of neurons
neuron_count = 30

# number of input type neurons
input_neuron_count = 10

# number of groups
group_count = 5

# number of connections
edge_count = 40

# value each neuron is initialized with
initial_membrane_potential = -55.0

# minimum potential at which a neuron will fire
activation_threshold = -55.0

# value that each neuron is set to after firing
refractory_membrane_potential = -70.0

# duration in milliseconds
refractory_duration = 3.0

# tau for the linearlization of the decay function
tau = 100.0

# input neuron probability of success
poisson_prob_of_success = 0.01

[debug]
# Options are
# INFO
# DEBUG
# DEBUG2
# DEBUG3
# DEBUG4
level = "DEBUG2"

[decay]
# Value that each neuron decays every wait_time * wait_loops
value = 1


[random]
# options are 'time' for using the current time, or an integer (as a string e.g. "1")
seed = "1"

[runtime_vars]
# in seconds
runtime = 10

# file to read input from
input_file = "./input_files/test"
