[neuron]

# number of neurons
neuron_count = 6

# number of groups
group_count = 2

# number of connections
edge_count = 4

# in milliseconds
wait_time = 100

# integer
wait_loops = 5

# value each neuron is initialized with
initial_membrane_potential = -55.0

# minimum potential at which a neuron will fire
activation_threshold = -55.0

# value that each neuron is set to after firing
refractory_membrane_potential = -70.0

[debug]
# Options are
# INFO
# DEBUG
# DEBUG2
# DEBUG3
# DEBUG4
level = "INFO"

[decay]
# Value that each neuron decays every wait_time * wait_loops
value = 1.0

[random]
# options are 'time' for using the current time, or an integer (as a string e.g. "1")
seed = "time"

[runtime_vars]
# in seconds
runtime = 20
