[neuron]
# NOTE: both the number of neurons and the number of input neurons
#       must be divisible by the number of groups

# number of neurons
neuron_count = 650

# number of input type neurons
input_neuron_count = 600

# number of groups
group_count = 5

# number of connections
# option can be "MAX" for maximum edges
edge_count = "MAX"

# refractory_duration
refractory_duration = 0.5

# value each neuron is initialized with
initial_membrane_potential = -55.0

# minimum potential at which a neuron will fire
activation_threshold = -55.0

# value that each neuron is set to after firing
refractory_membrane_potential = -70.0

#  tau for the linearlization of the decay function
tau = 100.0

#  poisson_prob_of_success
poisson_prob_of_success = 0.5
[debug]
# Options are
# NONE
# INFO
# DEBUG
# DEBUG2
# DEBUG3
# DEBUG4
level = "NONE"

[random]
# options are 'time' for using the current time, or an integer (as a string e.g. "1")
seed = "time"

[runtime_vars]
# Limit the log output to only Refractory events to limit log size
limit_log_size = true
# in seconds
runtime = 2.5
# name of output file (if left blank, a timestamp is used
output_file = ""
# file to read input from
input_file = "./input_files/mnist2.txt"
# format should be "x..y" for reading lines x to y (inclusive) or just x for a single line
line_range = "1..10"
